base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS
recovery_behaviors: {conservative_reset: clear_costmap_recovery/ClearCostmapRecovery, rotate_recovery: rotate_recovery/RotateRecovery, aggressive_reset: clear_costmap_recovery/ClearCostmapRecovery}
controller_frequency: 20.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
planner_frequency: 0.0
max_planning_retries: -1