joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

four_wheel_steering_controller:
  type: four_wheel_steering_controller/FourWheelSteeringController
  # wheel joint names
  front_wheel: ['front_left_wheel_joint', 'front_right_wheel_joint']
  rear_wheel: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
  # steering joint names
  front_steering: ['front_left_steer_joint', 'front_right_steer_joint']
  rear_steering: ['rear_left_steer_joint', 'rear_right_steer_joint']
  # odometry related
  publish_rate: 50.0
  # twist command related
  cmd_vel_timeout: 0.5
  base_frame_id: base_footprint
  enable_odom_tf: false # odom -> base_footprint
  enable_twist_cmd: false
  # velocity and acceleration limits
  linear:
    x:
      has_velocity_limits:     true
      has_acceleration_limits: true
      max_velocity:            1.667
      min_velocity:            -1.667
      max_acceleration:        1.0
      min_acceleration:        -1.0
  angular:
    z:
      has_velocity_limits:     true
      has_acceleration_limits: true
      max_velocity:            3.14
      min_velocity:            -3.14
      max_acceleration:        1.0
      min_acceleration:        -1.0
  # if either parameter is not available, we need to look up the value in the URDF
  track: 0.122
  wheel_steering_y_offset: 0.03
  wheel_radius: 0.026
  wheel_base: 0.154
  # params for covariances
  pose_covariance_diagonal:  [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

gazebo_ros_control:
  pid_gains:
    front_left_steer_joint: {p: 50.0, i: 1.0, d: 0.01}
    front_right_steer_joint: {p: 50.0, i: 1.0, d: 0.01}
    rear_left_steer_joint: {p: 50.0, i: 1.0, d: 0.01}
    rear_right_steer_joint: {p: 50.0, i: 1.0, d: 0.01}
    front_left_wheel_joint: {p: 0.01, i: 0.0, d: 0.0}
    front_right_wheel_joint: {p: 0.01, i: 0.0, d: 0.0}
    rear_left_wheel_joint: {p: 0.01, i: 0.0, d: 0.0}
    rear_right_wheel_joint: {p: 0.01, i: 0.0, d: 0.0}