four_wheel_steering_controller:
  type: four_wheel_steering_controller/FourWheelSteeringController
  # wheel joint names
  front_wheel: ['front_left_wheel_joint','front_right_wheel_joint']
  rear_wheel: ['rear_left_wheel_joint','rear_right_wheel_joint']
  # steering joint names
  front_steering: ['front_left_steer_joint','front_right_steer_joint']
  rear_steering: ['rear_left_steer_joint','rear_right_steer_joint']

  publish_rate: 50.0
  cmd_vel_timeout: 0.5
  base_frame_id: base_footprint
  enable_odom_tf: true # odom -> base_footprint
  enable_twist_cmd: false
  # velocity and acceleration limits
  linear:
    x:
      has_velocity_limits:     true
      has_acceleration_limits: true
      max_velocity:            1.0
      min_velocity:            -1.0
      max_acceleration:        0.5
      min_acceleration:        -0.5
  angular:
    z:
      has_velocity_limits:     true
      has_acceleration_limits: true
      max_velocity:            1.57079633
      min_velocity:            -1.57079633
      max_acceleration:        0.78539816
      min_acceleration:        -0.78539816

  track: 0.6
  wheel_steering_y_offset: 0.0
  wheel_radius: 0.067
  wheel_base: 0.6
  # params for covariances
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
