# gazebo_ros_control:
#   pid_gains:
#     front_left_steer_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -100000.0,i_clamp_max: 100000.0}
#     front_right_steer_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -100000.0,i_clamp_max: 100000.0}
#     rear_left_steer_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -100000.0,i_clamp_max: 100000.0}
#     rear_right_steer_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -100000.0,i_clamp_max: 100000.0}
#     front_left_wheel_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -100000.0,i_clamp_max: 100000.0}
#     front_right_wheel_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -100000.0,i_clamp_max: 100000.0}
#     rear_left_wheel_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -100000.0,i_clamp_max: 100000.0}
#     rear_right_wheel_joint: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: -100000.0,i_clamp_max: 100000.0}
