swerve_steering_controller:
  type: swerve_steering_controller/SwerveSteeringController
  # wheel joint names
  wheels: ['rear_right_wheel_joint','rear_left_wheel_joint','front_right_wheel_joint','front_left_wheel_joint']
  # steering joint names
  holders: ['rear_right_steer_joint','rear_left_steer_joint','front_right_steer_joint','front_left_steer_joint']

  publish_rate: 50
  base_frame_id: base_footprint
  odom_frame_id: odom
  enable_odom_tf: false # odom -> base_footprint
  # velocity and acceleration limits
  linear:
    x:
      has_velocity_limits:     true
      has_acceleration_limits: true
      max_velocity:            1.0
      min_velocity:            -1.0
      max_acceleration:        0.5
      min_acceleration:        -0.5
    y:
      has_velocity_limits:     true
      has_acceleration_limits: true
      max_velocity:            1.0
      min_velocity:            -1.0
      max_acceleration:        0.5
      min_acceleration:        -0.5
  angular:
    z:
      has_velocity_limits:     true
      has_acceleration_limits: true
      max_velocity:            1.57079633
      min_velocity:            -1.57079633
      max_acceleration:        0.78539816
      min_acceleration:        -0.78539816

  radii: [0.067, 0.067, 0.067, 0.067]
  limitless: [false, false, false, false]
  offsets: [0.0, 0.0, 0.0, 0.0]
  positions: [[-0.3,-0.3], [-0.3,0.3], [0.3,-0.3], [0.3,0.3]]
  limits: [[-3.14159265,3.14159265], [-3.14159265,3.14159265], [-3.14159265,3.14159265], [-3.14159265,3.14159265]]
  # params for covariances
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
