min_particles: 100
max_particles: 5000
kld_err: 0.01
kld_z: 0.99
update_min_d: 0.2
update_min_a: 0.5
resample_interval: 1
transform_tolerance: 0.1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
# initial_pose_x: 
# initial_pose_y: 
# initial_pose_a: 
# initial_cov_xx: 
# initial_cov_yy: 
# initial_cov_aa: 
gui_publish_rate: 10.0
# save_pose_rate: 
use_map_topic: true
first_map_only: true
# selective_resampling: 

# laser_min_range: 
# laser_max_range: 
laser_max_beams: 60
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1 
laser_likelihood_max_dist: 2.0
laser_model_type: beam

odom_model_type: diff-corrected
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.8
odom_alpha4: 0.2
odom_alpha5: 0.1
odom_frame_id: odom
# base_frame_id: 
# global_frame_id: 
# tf_broadcast: 