# http://docs.ros.org/en/noetic/api/robot_localization/html/state_estimation_nodes.html
# base parameters

frequency: 30
# sensor_timeout: 
two_d_mode: true

map_frame: map
odom_frame: odom
base_link_frame: base_footprint
# base_link_frame_output: 
world_frame: odom

transform_time_offset: 0.0
transform_timeout: 0.0

# four_wheel_steering_controller
odom0: /four_wheel_steering_controller/odom # (50 Hz)
odom0_config:  [false, false, false,
                false, false, false,
                true, false, false,
                false, false, false,
                false, false, false]
odom0_queue_size: 5
odom0_differential: false
odom0_relative: false
# odom0_nodelay:

# imu
imu0: /imu # (20 Hz)
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
imu0_queue_size: 5
imu0_differential: false
imu0_relative: true
# imu0_nodelay:

initial_state: [0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0]
publish_tf: true # odom -> base_footprint
publish_acceleration: false
permit_corrected_publication: false
print_diagnostics: false

# advanced parameters

# use_control: false
# stamped_control: false
# control_timeout: 
# control_config:  [true, true, false,
#                   false, false, true]

# acceleration_limits: [0.0, 0.0, 0.0,
#                       0.0, 0.0, 0.0]
# acceleration_gains: [0.0, 0.0, 0.0,
#                      0.0, 0.0, 0.0]
# deceleration_gains: [0.0, 0.0, 0.0,
#                      0.0, 0.0, 0.0]
# smooth_lagged_data: 
# history_length: 
# debug: false
# debug_out_file: 

# конфиг ковариационных матриц взят с https://github.com/introlab/rtabmap_ros/blob/c1d1c01d5d732784ceb6b225ebf6eebdb700ceb0/rtabmap_examples/launch/sensor_fusion.launch#L111
# Q - ковариационная матрица шума процесса - дисперсия переменных состояния
process_noise_covariance:  [0.005, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0.005, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0.006, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0.0025, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0.0025, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.002, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# dynamic_process_noise_covariance: true

# P - начальное значение ковариационной матрицы оценки состояния (дисперсии переменных))
# рекомендуется ставить значения немного больше чем дисперсий переменных
initial_estimate_covariance: [1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# reset_on_time_jump: 
# predict_to_current_time: true
# disabled_at_startup: false