# http://wiki.ros.org/joint_state_publisher
# robot_description: None
# dependent_joints: None
# rate: 10
# source_list: []
# use_mimic_tags: True
# zeros: {}
# use_smallest_joint_limits: True
# publish_default_positions: True
# publish_default_velocities: False
# publish_default_efforts: False