# http://docs.ros.org/en/noetic/api/robot_localization/html/navsat_transform_node.html

frequency: 10
delay: 1
magnetic_declination_radians: 0
yaw_offset: 0
zero_altitude: true
broadcast_utm_transform: true
use_odometry_yaw: false
wait_for_datum: false
broadcast_utm_transform_as_parent_frame: false
transform_timeout: 0
